apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "issuer"
spec:
  tls:
  - hosts:
    - test-apache.odva.fun
    secretName: letsencrypt
  rules:
    - host: test-apache.odva.fun
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: test-app-service
                port:
                  number: 5678