kind: Pod
apiVersion: v1
metadata:
  name: test-app-pod
  labels:
    app: test-app
spec:
  containers:
    - name: test-app-container
      image: httpd:2.4
      volumeMounts:
      - mountPath: /usr/local/apache2/htdocs/
        name: site-volume
  volumes:
  - name: site-volume
    hostPath:
      path: /root/test
      type: Directory
