kind: Pod
apiVersion: v1
metadata:
  name: nginx-app-pod
  namespace: nginx-app
  labels:
    app: nginx-app
spec:
  containers:
  - name: nginx-app-container
    image: httpd:2.4
    securityContext:
        privileged: true
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs/
      name: nginx-app-volume
  volumes:
  - name: nginx-app-volume
    hostPath:
      path: /home/zaur/test-nginx