on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    name: main
    steps:
    - name: notify
      id: notifier
      uses: z-z/gh-telegram-notifier-action@v0.9.5
      with:
        botApiKey: '1711705034:AAEFbiXWsXJZj9QLdP_-PUQ9Q7PFz2-gHHI'
        chats: '-1001397052454'
        msg: ❌ ${{ github.actor }} сломал выкат ${{ toJson(github.context) }}.
